version: "3.8"

services:

  mailhog:
    image: mailhog/mailhog:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailhog-http.rule=Host(`mailhog.${DOMAIN:-local}`)
      - traefik.http.routers.mailhog-http.entrypoints=http
      - traefik.http.routers.mailhog-http.middlewares=https-redirect
      - traefik.http.routers.mailhog-https.rule=Host(`mailhog.${DOMAIN:-local}`)
      - traefik.http.routers.mailhog-https.entrypoints=https
      - traefik.http.routers.mailhog-https.tls=true
      - traefik.http.routers.mailhog-https.tls.certresolver=le
      - traefik.http.services.mailhog.loadbalancer.server.port=8025
    networks:
      - traefik-public

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD:-nopassword}
      MYSQL_DATABASE: ${DATABASE:-symfony}
    volumes:
      - mysql-data:/var/lib/mysql:rw,delegated
    networks:
      - traefik-public

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadmin-http.rule=Host(`phpmyadmin.${DOMAIN:-local}`)
      - traefik.http.routers.phpmyadmin-http.entrypoints=http
      - traefik.http.routers.phpmyadmin-http.middlewares=https-redirect
      - traefik.http.routers.phpmyadmin-https.rule=Host(`phpmyadmin.${DOMAIN:-local}`)
      - traefik.http.routers.phpmyadmin-https.entrypoints=https
      - traefik.http.routers.phpmyadmin-https.tls=true
      - traefik.http.routers.phpmyadmin-https.tls.certresolver=le
      - traefik.http.services.phpmyadmin.loadbalancer.server.port=80
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - traefik-public

  rabbitmq:
    image: rabbitmq:3.11-management
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: ${PASSWORD:-nopassword}
    labels:
      - traefik.enable=true
      - traefik.http.routers.rabbitmq-http.rule=Host(`rabbitmq.${DOMAIN:-local}`)
      - traefik.http.routers.rabbitmq-http.entrypoints=http
      - traefik.http.routers.rabbitmq-http.middlewares=https-redirect
      - traefik.http.routers.rabbitmq-https.rule=Host(`rabbitmq.${DOMAIN:-local}`)
      - traefik.http.routers.rabbitmq-https.entrypoints=https
      - traefik.http.routers.rabbitmq-https.tls=true
      - traefik.http.routers.rabbitmq-https.tls.certresolver=le
      - traefik.http.services.rabbitmq.loadbalancer.server.port=15672
    networks:
      - traefik-public

  symfony:
    image: aartintelligent/app-symfony:6.2
    labels:
      - traefik.enable=true
      - traefik.http.routers.symfony-http.rule=Host(`symfony.${DOMAIN:-local}`)
      - traefik.http.routers.symfony-http.entrypoints=http
      - traefik.http.routers.symfony-http.middlewares=https-redirect
      - traefik.http.routers.symfony-https.rule=Host(`symfony.${DOMAIN:-local}`)
      - traefik.http.routers.symfony-https.entrypoints=https
      - traefik.http.routers.symfony-https.tls=true
      - traefik.http.routers.symfony-https.tls.certresolver=le
      - traefik.http.services.symfony.loadbalancer.server.port=8080
    links:
      - mailhog
      - mysql
      - rabbitmq
    depends_on:
      - mailhog
      - mysql
      - rabbitmq
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true

volumes:
  mysql-data:
