version: "3.8"

services:

  opensearch:
    image: opensearchproject/opensearch:${VERSION:=2.6.0}
    command: >
      bash -c '
        bin/opensearch-plugin install analysis-phonetic;
        bin/opensearch-plugin install analysis-icu;
        exec /usr/share/opensearch/opensearch-docker-entrypoint.sh opensearch;
      '
    environment:
      - discovery.type=single-node
    labels:
      - traefik.enable=true
      - traefik.http.routers.opensearch-http.rule=Host(`opensearch.${DOMAIN:=local}`)
      - traefik.http.routers.opensearch-http.entrypoints=http
      - traefik.http.routers.opensearch-http.middlewares=https-redirect
      - traefik.http.routers.opensearch-https.rule=Host(`opensearch.${DOMAIN:=local}`)
      - traefik.http.routers.opensearch-https.entrypoints=https
      - traefik.http.routers.opensearch-https.tls=true
      - traefik.http.routers.opensearch-https.tls.certresolver=le
      - traefik.http.services.opensearch.loadbalancer.server.port=9200
    volumes:
      - opensearch-data:/usr/share/opensearch/data:rw,delegated
    networks:
      - traefik-public

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:${VERSION:=2.6.0}
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    labels:
      - traefik.enable=true
      - traefik.http.routers.opensearch-dashboards-http.rule=Host(`opensearch-dashboards.${DOMAIN:=local}`)
      - traefik.http.routers.opensearch-dashboards-http.entrypoints=http
      - traefik.http.routers.opensearch-dashboards-http.middlewares=https-redirect
      - traefik.http.routers.opensearch-dashboards-https.rule=Host(`opensearch-dashboards.${DOMAIN:=local}`)
      - traefik.http.routers.opensearch-dashboards-https.entrypoints=https
      - traefik.http.routers.opensearch-dashboards-https.tls=true
      - traefik.http.routers.opensearch-dashboards-https.tls.certresolver=le
      - traefik.http.services.opensearch-dashboards.loadbalancer.server.port=5601
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true

volumes:
  opensearch-data:
