version: "3.8"

services:

  redis:
    image: redis:${VERSION:-7.0}
    volumes:
      - redis-data:/data:rw,delegated
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true

volumes:
  redis-data:
