version: "3.8"

services:

  traefik:
    image: traefik:${TRAEFIK_VERSION:-latest}
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=${EMAIL:-fake@mail.local}
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --log
      - --api
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.traefik-public-http.rule=Host(`traefik.${DOMAIN:-local}`)
      - traefik.http.routers.traefik-public-http.entrypoints=http
      - traefik.http.routers.traefik-public-http.middlewares=https-redirect
      - traefik.http.routers.traefik-public-https.rule=Host(`traefik.${DOMAIN:-local}`)
      - traefik.http.routers.traefik-public-https.entrypoints=https
      - traefik.http.routers.traefik-public-https.tls=true
      - traefik.http.routers.traefik-public-https.service=api@internal
      - traefik.http.routers.traefik-public-https.tls.certresolver=le
      - traefik.http.services.traefik-public.loadbalancer.server.port=8080
    volumes:
      - traefik-data:/certificates
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - '80:80'
      - '443:443'

  nginx:
    image: aartintelligent/app-nginx:${NGINX_VERSION:-latest}
    labels:
      - traefik.enable=true
      - traefik.http.routers.magento-http.rule=Host(`magento.${DOMAIN:-local}`)
      - traefik.http.routers.magento-http.entrypoints=http
      - traefik.http.routers.magento-http.middlewares=https-redirect
      - traefik.http.routers.magento-https.rule=Host(`magento.${DOMAIN:-local}`)
      - traefik.http.routers.magento-https.entrypoints=https
      - traefik.http.routers.magento-https.tls=true
      - traefik.http.routers.magento-https.tls.certresolver=le
      - traefik.http.services.magento.loadbalancer.server.port=8080
    volumes:
      - ./src:/var/www:rw,delegated
    depends_on:
      - traefik

volumes:
  traefik-data:
