version: "3.8"

services:

  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION:-latest}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer-http.rule=Host(`portainer.${DOMAIN:-local}`)
      - traefik.http.routers.portainer-http.entrypoints=http
      - traefik.http.routers.portainer-http.middlewares=https-redirect
      - traefik.http.routers.portainer-https.rule=Host(`portainer.${DOMAIN:-local}`)
      - traefik.http.routers.portainer-https.entrypoints=https
      - traefik.http.routers.portainer-https.tls=true
      - traefik.http.routers.portainer-https.tls.certresolver=le
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true

volumes:
  portainer-data:
