version: "3.8"

services:

  mysql:
    image: mysql:${VERSION:-8.0}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD:-nopassword}
    volumes:
      - mysql-data:/var/lib/mysql:rw,delegated
    networks:
      - traefik-public

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadmin-http.rule=Host(`phpmyadmin.${DOMAIN:-local}`)
      - traefik.http.routers.phpmyadmin-http.entrypoints=http
      - traefik.http.routers.phpmyadmin-http.middlewares=https-redirect
      - traefik.http.routers.phpmyadmin-https.rule=Host(`phpmyadmin.${DOMAIN:-local}`)
      - traefik.http.routers.phpmyadmin-https.entrypoints=https
      - traefik.http.routers.phpmyadmin-https.tls=true
      - traefik.http.routers.phpmyadmin-https.tls.certresolver=le
      - traefik.http.services.phpmyadmin.loadbalancer.server.port=80
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true

volumes:
  mysql-data:
