version: '3.8'

services:
  
  mysql_db1:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1.0'
          memory: 7189M
        reservations:
          cpus: '1.5'
          memory: 6144M
      placement:
        constraints:
          - node.role == worker
          - node.labels.mysql_type == mysql_db1
    secrets:
      - source: mysql_root_password
        target: /run/secrets/mysql_root_password
        mode: 0444
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
    volumes:
      - mysql_db1_data:/var/lib/mysql
    networks:
      - mysql_cluster

  mysql_db2:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1.0'
          memory: 7189M
        reservations:
          cpus: '1.5'
          memory: 6144M
      placement:
        constraints:
          - node.role == worker
          - node.labels.mysql_type == mysql_db2
    secrets:
      - source: mysql_root_password
        target: /run/secrets/mysql_root_password
        mode: 0444
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
    volumes:
      - mysql_db2_data:/var/lib/mysql
    networks:
      - mysql_cluster

  mysql_db3:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1.0'
          memory: 7189M
        reservations:
          cpus: '1.5'
          memory: 6144M
      placement:
        constraints:
          - node.role == worker
          - node.labels.mysql_type == mysql_db3
    secrets:
      - source: mysql_root_password
        target: /run/secrets/mysql_root_password
        mode: 0444
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
    volumes:
      - mysql_db3_data:/var/lib/mysql
    networks:
      - mysql_cluster

  mysql_router:
    image: mysql/mysql-router:8.0
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1.0'
          memory: 3072M
        reservations:
          cpus: '1.5'
          memory: 2560M
      placement:
        constraints:
          - node.role == worker
          - node.labels.mysql_type == mysql_router
    secrets:
      - source: mysql_root_password
        target: /run/secrets/mysql_root_password
        mode: 0444
      - source: mysql_router
        target: /run/secrets/mysql_router.conf
        mode: 0777
    environment:
      MYSQL_HOST: mysql_router
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: /run/secrets/mysql_root_password
      MYSQL_INNODB_NUM_MEMBERS: 3
    ports:
      - '6446:6446'
    networks:
      - mysql_cluster

volumes:
  mysql_db1_data:
    driver: local
  mysql_db2_data:
    driver: local
  mysql_db3_data:
    driver: local

networks:
  mysql_cluster:

secrets:
  mysql_root_password:
    external: true
  mysql_router:
    external: true
