version: '3.8'

services:
  
  mysql_db1:
    image: mysql:8.0
    command: [ "--server-id=mysql_db1", "--log-bin=mysql-bin" ]
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1.0'
          memory: 7189M
        reservations:
          cpus: '1.5'
          memory: 6144M
      placement:
        constraints:
          - node.role == worker
          - node.labels.mysql_type == mysql_db1
    secrets:
      - source: mysql_root_password
        target: /run/secrets/mysql_root_password
        mode: 0444
    environment:
      MYSQL_HOST: mysql_db1
      MYSQL_PORT: 3306
      MYSQL_USER: rootless
      MYSQL_PASSWORD: /run/secrets/mysql_root_password
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
    volumes:
      - mysql_db1_data:/var/lib/mysql
    networks:
      - mysql_cluster

  mysql_db2:
    image: mysql:8.0
    command: [ "--server-id=mysql_db2", "--log-bin=mysql-bin" ]
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1.0'
          memory: 7189M
        reservations:
          cpus: '1.5'
          memory: 6144M
      placement:
        constraints:
          - node.role == worker
          - node.labels.mysql_type == mysql_db2
    secrets:
      - source: mysql_root_password
        target: /run/secrets/mysql_root_password
        mode: 0444
    environment:
      MYSQL_HOST: mysql_db1
      MYSQL_PORT: 3306
      MYSQL_USER: rootless
      MYSQL_PASSWORD: /run/secrets/mysql_root_password
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
    volumes:
      - mysql_db2_data:/var/lib/mysql
    networks:
      - mysql_cluster

  mysql_db3:
    image: mysql:8.0
    command: [ "--server-id=mysql_db3", "--log-bin=mysql-bin" ]
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1.0'
          memory: 7189M
        reservations:
          cpus: '1.5'
          memory: 6144M
      placement:
        constraints:
          - node.role == worker
          - node.labels.mysql_type == mysql_db3
    secrets:
      - source: mysql_root_password
        target: /run/secrets/mysql_root_password
        mode: 0444
    environment:
      MYSQL_HOST: mysql_db1
      MYSQL_PORT: 3306
      MYSQL_USER: rootless
      MYSQL_PASSWORD: /run/secrets/mysql_root_password
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
    volumes:
      - mysql_db3_data:/var/lib/mysql
    networks:
      - mysql_cluster

  mysql_router:
    image: mysql/mysql-router:8.0
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1.0'
          memory: 3072M
        reservations:
          cpus: '1.5'
          memory: 2560M
      placement:
        constraints:
          - node.role == worker
          - node.labels.mysql_type == mysql_router
    secrets:
      - source: mysql_router
        target: /run/secrets/mysql_router.conf
        mode: 0444
      - source: mysql_root_password
        target: /run/secrets/mysql_root_password
        mode: 0444
    environment:
      MYSQL_HOST: mysql_router
      MYSQL_PORT: 3306
      MYSQL_USER: rootless
      MYSQL_PASSWORD: /run/secrets/mysql_root_password
      MYSQL_ROUTER_CONFIG: /run/secrets/mysql_router.conf
    ports:
      - '6446:6446'
    networks:
      - mysql_cluster

volumes:
  mysql_db1_data:
  mysql_db2_data:
  mysql_db3_data:

networks:
  mysql_cluster:

secrets:
  mysql_config:
    external: true
  mysql_root_password:
    external: true
  mysql_router:
    external: true
